move common and user/* stores
upstars-global/unity-core-modules pull request #45
Opened 2024-12-19 15:54 UTC by upstars-dmshevchenko

Closes: UN-406, UN-261, UN-254, UN-258, UN-259

2024-12-20 07:48 UTC, andrey-danilov commented on src/helpers/currencyOfCountry/currencyCodesOfCountry.ts
> +export const currencyCodesOfCountry = {
у нас уже есть такой енам отдельно лежит

2024-12-20 07:49 UTC, andrey-danilov commented on src/helpers/currencyOfCountry/index.ts
> +export * from "./currencyCodesOfCountry";
мы решили избавляться от индекс файлов

2024-12-20 07:59 UTC, andrey-danilov commented on src/store/games/gamesStore.ts
> +export interface IGamesCommonStoreDefaultOptions {
если он используется еще где то то может его в папку models определить?

2024-12-20 08:05 UTC, andrey-danilov commented on src/store/user/consts.ts
> +export const TEST_GROUP_ID = 21;
я думаю этот файл стоит оставить в фронтере в config

2024-12-20 08:12 UTC, upstars-dmshevchenko commented on src/store/user/consts.ts
> +export const TEST_GROUP_ID = 21;
ну вот куда тогда его положить? потому что стор/юзер нету уже)

2024-12-20 08:15 UTC, upstars-dmshevchenko commented on src/store/games/gamesStore.ts
> +export interface IGamesCommonStoreDefaultOptions {
учитывая что это исключительно для описания аргументов в конкретном месте, то я бы не выносил такое. Оно нигде больше не переиспользуется. Чисто чтоб не писать в 2 местах одинаково {prop1:string, prop2:number} )))

2024-12-20 08:16 UTC, upstars-dmshevchenko commented on src/helpers/currencyOfCountry/index.ts
> +export * from "./currencyCodesOfCountry";
я не против тут, тогда папку убрать нужно. Но индекс файлы будут все равно когда на билд перейдем, потому не избавишься полностью))

2024-12-20 08:19 UTC, upstars-dmshevchenko commented on src/helpers/currencyOfCountry/currencyCodesOfCountry.ts
> +export const currencyCodesOfCountry = {
я вижу только один енам тут, но не удалил во фронтере(

2024-12-20 08:55 UTC, andrey-danilov commented on src/store/user/userStatuses.ts
> +import { VIP_CLUB_STATUSES } from "@components/VipClub/consts";
лучше выносить такое в config папку фронтеры что бы не было потом проблем на кинге

2024-12-20 08:56 UTC, andrey-danilov commented on src/store/user/userStatuses.ts
> +import { STATUSES } from "@components/VipClub/constsNew";
аналогично

2024-12-20 08:57 UTC, andrey-danilov commented on src/store/user/vipAdventures.ts
>  import { formatDateVipAdv, VIP_ADV_GROUP } from "@modules/VipAdventures/consts";
аналогично папка config в фронтере

2024-12-20 08:59 UTC, andrey-danilov commented on src/types/common.ts
> +export interface IMapImages {
в папку models нужно перенести

2024-12-20 08:59 UTC, upstars-dmshevchenko commented on src/store/user/vipAdventures.ts
>  import { formatDateVipAdv, VIP_ADV_GROUP } from "@modules/VipAdventures/consts";
ну я специально не трогал, чтоб было как было

2024-12-20 08:59 UTC, andrey-danilov commented on src/types/levels.ts
> +interface IPersistentCompPoints {
в папку models нужно перенести

2024-12-20 09:01 UTC, upstars-dmshevchenko commented on src/store/user/vipAdventures.ts
>  import { formatDateVipAdv, VIP_ADV_GROUP } from "@modules/VipAdventures/consts";
я б для начала сформировал единый формат конфига, который бы уже скармливался в стор юнити модуля для переиспользования с одного места всем приложением

2024-12-20 09:03 UTC, upstars-dmshevchenko commented on src/store/user/userStatuses.ts
> +import { VIP_CLUB_STATUSES } from "@components/VipClub/consts";
в рамках задач по стору мне говорили не трогать такие импорты пока что)

2024-12-20 09:27 UTC, andrey-danilov commented on src/store/games/gamesStore.ts
> +export interface IGamesCommonStoreDefaultOptions {
просто смутил export 
если нигде не используется в проекте то тогда убрать export что бы не сбивал с толку

2024-12-20 09:28 UTC, andrey-danilov commented on src/store/user/consts.ts
> +export const TEST_GROUP_ID = 21;
ну создать файл в папке config user и туда все это перенести

2024-12-20 09:30 UTC, andrey-danilov commented on src/store/user/userStatuses.ts
> +import { VIP_CLUB_STATUSES } from "@components/VipClub/consts";
возможно что то другое имели в виду но потом мы выстрелим себе в ногу так как импорты с алиасами(на проект будет разкиданы по всем папкам) в аналогичных случаях я и Ден выносив в папку config

2024-12-20 09:32 UTC, andrey-danilov commented on src/store/user/vipAdventures.ts
>  import { formatDateVipAdv, VIP_ADV_GROUP } from "@modules/VipAdventures/consts";
отписал выше в аналогичном коменте

2024-12-20 11:20 UTC, d-tashchi-upstars commented on package.json
> +    "vite-plugin-node-polyfills": "^0.22.0"
наверное забыл снести

2024-12-20 11:20 UTC, d-tashchi-upstars commented on package.json
> +  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
для чего єто?

2024-12-20 11:21 UTC, d-tashchi-upstars commented on src/consts/games.ts
єто проектные категории. на Кинге будет другой нейминг

2024-12-20 11:22 UTC, d-tashchi-upstars commented on src/controllers/CustomerIO.ts
> +const YOUR_SITE_ID = "fe1bbf5480bb59194b4c";
проектные креды нет смысла их в общак выносить

2024-12-20 11:26 UTC, d-tashchi-upstars commented on src/services/user.service.ts
> +    const ID_GROUP_FOR_PAIRED_ID = 543;
єто по хорошему бы тоже вынести.

2024-12-20 11:26 UTC, upstars-dmshevchenko commented on package.json
> +  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
автоматом проставляет при установке, удалю

2024-12-20 11:36 UTC, upstars-dmshevchenko commented on package.json
> +    "vite-plugin-node-polyfills": "^0.22.0"
без него билд не проходит локально, потому что не находит buffer полифил

2024-12-20 19:46 UTC, upstars-dmshevchenko commented on src/consts/games.ts
надо будет тоже на рефакторинг что-то придумать, потому что енам так не годится импортировать. Я б поменял на тип ключей возможных типов игр и по ним делать поиск на соответствие значения по переданому обьекту)) а то тут так теряем все преимущество енама и тайпскрипта

2024-12-20 21:41 UTC, upstars-dmshevchenko commented on src/services/user.service.ts
> +    const ID_GROUP_FOR_PAIRED_ID = 543;
done

2024-12-20 21:41 UTC, upstars-dmshevchenko commented on src/controllers/CustomerIO.ts
> +const YOUR_SITE_ID = "fe1bbf5480bb59194b4c";
done

2024-12-20 21:42 UTC, upstars-dmshevchenko commented on src/consts/games.ts
done

2024-12-20 21:42 UTC, upstars-dmshevchenko commented on package.json
> +  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
removed

2024-12-20 21:44 UTC, upstars-dmshevchenko commented on package.json
> +    "vite-plugin-node-polyfills": "^0.22.0"
пока оставил, далее придумаем если на билд перенесем, но реально я сколько пытался с разными способами оно из-за buffer в localeInCookie хелпере не собирало, потому что не находит где взять залепу для него при билде

2024-12-20 21:44 UTC, upstars-dmshevchenko commented on src/types/levels.ts
> +interface IPersistentCompPoints {
done

2024-12-20 21:44 UTC, upstars-dmshevchenko commented on src/types/common.ts
> +export interface IMapImages {
done

2024-12-20 21:44 UTC, upstars-dmshevchenko commented on src/store/user/userStatuses.ts
> +import { STATUSES } from "@components/VipClub/constsNew";
не трогаем пока, чтоб кинг проще было переносить

2024-12-20 22:29 UTC, upstars-dmshevchenko commented on src/store/user/vipAdventures.ts
>  import { formatDateVipAdv, VIP_ADV_GROUP } from "@modules/VipAdventures/consts";
done

2024-12-20 22:29 UTC, upstars-dmshevchenko commented on src/store/user/userStatuses.ts
> +import { STATUSES } from "@components/VipClub/constsNew";
done

2024-12-20 22:29 UTC, upstars-dmshevchenko commented on src/store/user/userStatuses.ts
> +import { VIP_CLUB_STATUSES } from "@components/VipClub/consts";
done

2024-12-20 22:29 UTC, upstars-dmshevchenko commented on src/store/user/consts.ts
> +export const TEST_GROUP_ID = 21;
done

2024-12-20 22:29 UTC, upstars-dmshevchenko commented on src/store/games/gamesStore.ts
> +export interface IGamesCommonStoreDefaultOptions {
done

2024-12-20 22:29 UTC, upstars-dmshevchenko commented on src/helpers/currencyOfCountry/index.ts
> +export * from "./currencyCodesOfCountry";
done

2024-12-20 22:29 UTC, upstars-dmshevchenko commented on src/helpers/currencyOfCountry/currencyCodesOfCountry.ts
> +export const currencyCodesOfCountry = {
done

2024-12-23 08:37 UTC, d-tashchi-upstars requested changes

2024-12-23 08:37 UTC, d-tashchi-upstars commented on src/services/games.ts
> +        const { data } = await http().get<Record<string, SlugCategoriesGames[]>>("/api/fe/config/menu-categories-games");
вынеси єто в апи/реквесты, вместе с логом.

2024-12-23 08:37 UTC, d-tashchi-upstars commented on src/store/common.ts
> +            const { data } = await http().get("/api/info/player_fields");
в апи реквесты вынести бы с логом

2024-12-23 09:31 UTC, upstars-dmshevchenko commented on src/store/common.ts
> +            const { data } = await http().get("/api/info/player_fields");
ой в сторах полно этого...))

2024-12-23 09:51 UTC, upstars-dmshevchenko commented on src/store/common.ts
> +            const { data } = await http().get("/api/info/player_fields");
готово

2024-12-23 09:51 UTC, upstars-dmshevchenko commented on src/services/games.ts
> +        const { data } = await http().get<Record<string, SlugCategoriesGames[]>>("/api/fe/config/menu-categories-games");
готово

2024-12-23 10:02 UTC, d-tashchi-upstars approved these changes

2024-12-23 10:08 UTC, merged